remove grunTester, remove error.out on success

diff --git a/testgrun b/testgrun
--- a/testgrun
+++ b/testgrun
@@ -19,4 +19,4 @@ do
     fi
 done
 
-[ -s error.out ] && exit 1 || echo "All test cases pass!"
+[ -s error.out ] && exit 1 || echo "All test cases pass!" && rm error.out
